# Exploring The Star Wars Dataset with The Pandas Library

In [3]:
import pandas as pd

If you don't have the pandas library installed you can install it with uncommenting the following:

In [4]:
#!pip install pandas

If you have the data set in your computer, you can use the path. Remember to replace backslash to slash: \ -> /
For example: "C:\Users\user1\star_wars\star_wars\csv\characters.csv" becomes "C:/Users/user1/star_wars/star_wars/csv/characters.csv"
You can also download the library from the Internet

**Use pandas read_csv function to read in the data**

In [5]:
df_characters = pd.read_csv("https://raw.githubusercontent.com/planetacomputer/starwars-full/main/characters.csv")

**Examine the top 2 rows**

In [3]:
df_characters.head(2)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
1,2,Leia Organa,Human,Female,1.50,49.0,Brown,Brown,Light,19.0,Alderaan,35.0,A leader in the Rebel Alliance and twin sister...

**Print the column names**

In [6]:
df_characters.columns

Index(['id', 'name', 'species', 'gender', 'height', 'weight', 'hair_color',
       'eye_color', 'skin_color', 'year_born', 'homeworld', 'year_died',
       'description'],
      dtype='object')

**Print the datatypes**

In [5]:
df_characters.dtypes

id               int64
name            object
species         object
gender          object
height         float64
weight         float64
hair_color      object
eye_color       object
skin_color      object
year_born      float64
homeworld       object
year_died      float64
description     object
dtype: object

## Exercises

### Selecting columns

Select only one column

In [41]:
df_characters[["name"]].head(3)

             name
0  Luke Skywalker
1     Leia Organa
2     Darth Vader

In [42]:
df_characters[["name","height"]].head(3)

             name  height
0  Luke Skywalker    1.72
1     Leia Organa    1.50
2     Darth Vader    2.02

In [43]:
df_characters.loc[:2, "name"]

0    Luke Skywalker
1       Leia Organa
2       Darth Vader
Name: name, dtype: object

In [44]:
df_characters[['height']].head()

   height
0    1.72
1    1.50
2    2.02
3    0.66
4    1.80

In [46]:
type(df_characters[['height']].head())

pandas.core.frame.DataFrame

Select multiple columns:

In [47]:
df_characters[["name","species","gender","height"]].head(3)

             name species  gender  height
0  Luke Skywalker   Human    Male    1.72
1     Leia Organa   Human  Female    1.50
2     Darth Vader   Human    Male    2.02

Extra exercise: first put the columns name in a list and then use the variable name instead

### Filtering

Select only lines where height is over 1.5 m

In [10]:
df_characters[df_characters["height"] > 1.5].head(3)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.

Under the hood pandas produces a boolean array and that is used to make selection

In [49]:
df_characters["height"] > 1.5 # condition

0      True
1     False
2      True
3     False
4      True
      ...
91     True
92     True
93     True
94     True
95    False
Name: height, Length: 96, dtype: bool

Filtering with multiple conditions when both conditions must be true, we use **&**. Syntax is the following: **df_characters[ (condition 1) & (condintion 2)]** Note that we use & instead of **and**.

In [12]:
df_characters[ ( df_characters["species"] == "Human") & ( df_characters["height"] > 2.0 ) ]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.

In [53]:
df_characters[(df_characters["species"] != "Human") & (df_characters["height"] > 1.5)]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52.0,Naboo,NaN,A clumsy Gungan who became a representative in...
19,20,C-3PO,Droid,NaN,1.71,NaN,NaN,NaN,Gold,112.0,Tatooine,NaN,A protocol droid fluent in over six million fo...
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.
28,29,Aayla Secura,Twi'lek,Female,1.78,55.0,Blue,Hazel,Blue,48.0,Ryloth,19.0,A Jedi Knight during the Clone Wars.
29,30,Admiral Ackbar,Mon Calamari,Male,1.80,72.0,NaN,Orange,Red,52.0,Mon Cala,35.0,A respected admiral in the Rebel Alliance.
32,33,Barriss Offee,Mirialan,Female,1.66,50.0,Black,Blue,Green,40.0,Mirial,19.0,A Jedi Padawan during the Clone Wars.
34,35,Bib Fortuna,Twi'lek,Male,1.93,65.0,NaN,Red,Pale,60.0,Ryloth,35.0,A majordomo for Jabba the Hutt.
35,36,Bossk,Trandoshan,Male,1.90,113.0,NaN,Red,Green,53.0,Trandosha,NaN,A feared bounty hunter.
39,40,Greedo,Rodian,Male,1.73,70.0,NaN,Black,Green,44.0,Rodia,0.0,A bounty hunter killed by Han Solo.
40,41,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
41,42,Jabba the Hutt,Hutt,Male,3.90,1358.0,NaN,Orange,Green,600.0,Nal Hutta,4.0,A notorious crime lord.
43,44,Kit Fisto,Nautolan,Male,1.96,87.0,NaN,Black,Green,48.0,Glee Anselm,19.0,A Jedi Master known for his underwater combat ...
46,47,Nien Nunb,Sullustan,Male,1.60,70.0,NaN,Black,Light,43.0,Sullust,NaN,A pilot who co-piloted the Millennium Falcon d...
47,48,Plo Koon,Kel Dor,Male,1.88,80.0,NaN,Black,Orange,44.0,Dorin,19.0,A Jedi Master known for his unique mask.
50,51,Shaak Ti,Togruta,Female,1.87,68.0,NaN,Black,Red,43.0,Shili,NaN,A Jedi Master and member of the Jedi High Coun...
54,55,Zam Wesell,Clawdite,Female,1.78,60.0,Brown,Yellow,Green,32.0,Zolan,22.0,A shape-shifting bounty hunter.
55,56,Ahsoka Tano,Togruta,Female,1.88,55.0,NaN,Blue,Orange,36.0,Shili,NaN,A former Jedi Padawan of Anakin Skywalker.
56,57,Asajj Ventress,Dathomirian,Female,1.70,55.0,NaN,Blue,Pale,57.0,Dathomir,19.0,A former Sith apprentice turned bounty hunter.
57,58,Cad Bane,Duros,Male,1.85,75.0,NaN,Red,Blue,62.0,Duro,NaN,A feared bounty hunter.
59,60,Savage Opress,Dathomirian,Male,2.18,100.0,NaN,Yellow,Pale,49.0,Dathomir,19.0,The brother of Darth Maul and a powerful Sith ...
60,61,Hondo Ohnaka,Weequay,Male,1.75,70.0,Black,Brown,Brown,45.0,Sriluur,NaN,A pirate and smuggler.
61,62,Pong Krell,Besalisk,Male,2.50,300.0,NaN,Yellow,Green,52.0,Ojom,19.0,A Jedi Master who fell to the dark side.
62,63,Mother Talzin,Dathomirian,Female,1.70,55.0,Black,Green,Pale,100.0,Dathomir,19.0,A powerful witch and leader of the Nightsisters.
66,67,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
75,76,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
79,80,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
88,89,Admiral Raddus,Mon Calamari,Male,1.80,72.0,NaN,Orange,Blue,50.0,Mon Cala,0.0,A respected admiral in the Rebel Alliance.
92,93,L3-37,Droid,NaN,1.80,NaN,NaN,Green,Gray,NaN,Unknown,10.0,A self-built piloting droid.

**Pandas logical operators are:**

& = bitwise AND operator

| = bitwise OR operator

~ = bitwise NOT operator

We can combine the operators. Here we choose characters whose eye_color is **not** Blue nor Brown or whose hair color is white

In [54]:
df_characters["skin_color"].value_counts()

skin_color
Light         50
Green         10
Dark           9
Pale           7
Blue           6
Brown          4
Orange         4
Red            2
Gold           1
White          1
White/Blue     1
Gray           1
Name: count, dtype: int64

In [55]:
df_characters["species"].value_counts()

species
Human             60
Droid              4
Twi'lek            4
Dathomirian        3
Unknown            2
Togruta            2
Chiss              2
Mon Calamari       2
Gungan             1
Mirialan           1
Yoda's species     1
Wookiee            1
Trandoshan         1
Nautolan           1
Sullustan          1
Hutt               1
Rodian             1
Dug                1
Kel Dor            1
Clawdite           1
Ewok               1
Duros              1
Weequay            1
Besalisk           1
Ardennian          1
Name: count, dtype: int64

## EXERCISES

!!!!! **Exercise 1 - 6 you have to be able to present **without** computer, so learn them by ❤️** !!!!!

### Exercise 1 - ✏️🧠

Select from df_characters only columns **name, species, hair_color, eye_color**

In [73]:
# option 1:
df_characters[["name","species","hair_color","eye_color"]]
# option2:
df_characters.loc[:,['name','species','hair_color','eye_color']]
# option 3:
df_characters.filter(items=['name', 'species', 'hair_color', 'eye_color'])

              name         species hair_color eye_color
0   Luke Skywalker           Human      Blond      Blue
1      Leia Organa           Human      Brown     Brown
2      Darth Vader           Human        NaN    Yellow
3             Yoda  Yoda's species      White     Brown
4         Han Solo           Human      Brown     Hazel
..             ...             ...        ...       ...
91      Enfys Nest           Human        Red     Brown
92           L3-37           Droid        NaN     Green
93         Beckett           Human      Brown      Blue
94             Val           Human      Black     Brown
95      Rio Durant       Ardennian        NaN     Black

[96 rows x 4 columns]

### Exercise 2 - ✏️🧠

Select from df_characters that are less than 1.0 meter

In [75]:
# option 1:
df_characters[df_characters['height']<10]
# option 2:
df_characters.loc[df_characters['height']<10]
# option 3:
df_characters.query("height < 10")

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
1,2,Leia Organa,Human,Female,1.50,49.0,Brown,Brown,Light,19.0,Alderaan,35.0,A leader in the Rebel Alliance and twin sister...
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896.0,Unknown,4.0,A wise and powerful Jedi Master.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,Enfys Nest,Human,Female,1.68,55.0,Red,Brown,Light,19.0,Unknown,NaN,A rebel and leader of the Cloud-Riders.
92,93,L3-37,Droid,NaN,1.80,NaN,NaN,Green,Gray,NaN,Unknown,10.0,A self-built piloting droid.
93,94,Beckett,Human,Male,1.85,80.0,Brown,Blue,Light,50.0,Glee Anselm,10.0,A criminal and mentor to Han Solo.
94,95,Val,Human,Female,1.75,55.0,Black,Brown,Dark,30.0,Unknown,10.0,A member of Beckett's crew.
95,96,Rio Durant,Ardennian,Male,1.40,40.0,NaN,Black,Blue,40.0,Ardennia,10.0,A four-armed pilot in Beckett's crew.

### Exercise 3 - ✏️🧠

Select from df_characters whose skin color is **Green** and select only columns **name, species, gender**

In [78]:
# option 1:
df_characters.loc[df_characters['skin_color']=='Green',['name','species','gender']]
# option 2:
df_characters[df_characters['skin_color'] == 'Green'][['name', 'species', 'gender']]
# option 3:
df_characters.query("skin_color =='Green'")[['name','species','gender']]
# option 4:
df_characters[df_characters['skin_color'] == 'Green'].filter(items=['name', 'species', 'gender'])

              name         species  gender
3             Yoda  Yoda's species    Male
32   Barriss Offee        Mirialan  Female
35           Bossk      Trandoshan    Male
39          Greedo          Rodian    Male
40   Hera Syndulla         Twi'lek  Female
41  Jabba the Hutt            Hutt    Male
43       Kit Fisto        Nautolan    Male
54      Zam Wesell        Clawdite  Female
61      Pong Krell        Besalisk    Male
75   Hera Syndulla         Twi'lek  Female

### Exercise 4 - ✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **Red**.

In [ ]:
# option 1:
df_characters[(df_characters['eye_color'] == 'Blue') & (df_characters['hair_color']=="Red")]
# option 2:
condition = (df_characters['eye_color']=='Blue') & (df_characters['hair_color']=='Red')
df_characters[condition]
# option 3:
df_characters.loc[(df_characters['eye_color']=='Blue') & (df_characters['hair_color']=='Red')]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
24,25,General Hux,Human,Male,1.85,75.0,Red,Blue,Light,0.0,Arkanis,35.0,A general in the First Order.
45,46,Mon Mothma,Human,Female,1.70,55.0,Red,Blue,Light,48.0,Chandrila,NaN,A leader in the Rebel Alliance.

### Exercise 5 -✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **NOT** **Red**.

In [28]:
# option 1:
df_characters[(df_characters['eye_color']=='Blue')&(df_characters['hair_color']!='Red')]
# option 2:
condition = (df_characters['eye_color'] == 'Blue') & (df_characters['hair_color'] != 'Red')
result = df_characters[condition]
# option 3:
df_characters.loc[(df_characters['eye_color'] == 'Blue') & (df_characters['hair_color'] != 'Red')]
# option 4:
df_characters.query("eye_color == 'Blue' and hair_color != 'Red'")
# option 5:
df_characters[(df_characters['eye_color'] == 'Blue') & ~(df_characters['hair_color'] == 'Red')]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
8,9,Anakin Skywalker,Human,Male,1.88,84.0,Blond,Blue,Light,41.0,Tatooine,4.0,A Jedi Knight who fell to the dark side and be...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.
30,31,Admiral Piett,Human,Male,1.80,75.0,Brown,Blue,Light,59.0,Axxila,4.0,An Imperial officer serving under Darth Vader.
32,33,Barriss Offee,Mirialan,Female,1.66,50.0,Black,Blue,Green,40.0,Mirial,19.0,A Jedi Padawan during the Clone Wars.
36,37,Captain Phasma,Human,Female,2.00,75.0,Blonde,Blue,Light,15.0,Parnassos,35.0,A high-ranking officer in the First Order.
40,41,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
42,43,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
44,45,Lobot,Human,Male,1.75,75.0,NaN,Blue,Light,47.0,Bespin,NaN,A cyborg aide to Lando Calrissian.
55,56,Ahsoka Tano,Togruta,Female,1.88,55.0,NaN,Blue,Orange,36.0,Shili,NaN,A former Jedi Padawan of Anakin Skywalker.
56,57,Asajj Ventress,Dathomirian,Female,1.70,55.0,NaN,Blue,Pale,57.0,Dathomir,19.0,A former Sith apprentice turned bounty hunter.
58,59,Captain Rex,Human,Male,1.83,80.0,Blond,Blue,Light,32.0,Kamino,NaN,A clone trooper captain who served under Anaki...
65,66,Kallus,Human,Male,1.88,85.0,Blond,Blue,Light,40.0,Coruscant,NaN,An Imperial agent who defected to the Rebel Al...
69,70,Orson Krennic,Human,Male,1.85,80.0,White,Blue,Light,51.0,Lexrul,0.0,The director of the Empire's Advanced Weapons ...
75,76,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
76,77,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
82,83,Orson Krennic,Human,Male,1.85,80.0,White,Blue,Light,51.0,Lexrul,0.0,The director of the Empire's Advanced Weapons ...
89,90,Dryden Vos,Human,Male,1.85,80.0,Blond,Blue,Light,35.0,Corellia,10.0,A crime lord in the Crimson Dawn syndicate.
93,94,Beckett,Human,Male,1.85,80.0,Brown,Blue,Light,50.0,Glee Anselm,10.0,A criminal and mentor to Han Solo.

### Exercise 6 - ✏️🧠

Find all characters who are taller than 180 cm AND weigh more than 80 kg.

In [7]:
# option 1:
df_characters[(df_characters['height']>1.8) & (df_characters['weight']>80)]
# option 2:
condition = (df_characters['height']>1.8) & (df_characters['weight']>80)
df_characters[condition]
# option 3:
df_characters.query('height > 1.8 and weight > 80')
# option 4:
df_characters.loc[(df_characters['height']>1.8) & (df_characters['weight']>80)]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
6,7,Obi-Wan Kenobi,Human,Male,1.82,81.0,White,Blue-gray,Light,57.0,Stewjon,0.0,A Jedi Master who mentored Anakin and Luke Sky...
8,9,Anakin Skywalker,Human,Male,1.88,84.0,Blond,Blue,Light,41.0,Tatooine,4.0,A Jedi Knight who fell to the dark side and be...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.
11,12,Mace Windu,Human,Male,1.88,84.0,NaN,Brown,Dark,72.0,Haruun Kal,19.0,A Jedi Master and member of the Jedi High Coun...
17,18,Kylo Ren,Human,Male,1.89,89.0,Black,Brown,Light,5.0,Chandrila,35.0,A dark side user formerly known as Ben Solo.
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.
31,32,Bail Organa,Human,Male,1.91,86.0,Black,Brown,Light,67.0,Alderaan,0.0,A senator and adoptive father of Leia Organa.
35,36,Bossk,Trandoshan,Male,1.90,113.0,NaN,Red,Green,53.0,Trandosha,NaN,A feared bounty hunter.
41,42,Jabba the Hutt,Hutt,Male,3.90,1358.0,NaN,Orange,Green,600.0,Nal Hutta,4.0,A notorious crime lord.
42,43,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
43,44,Kit Fisto,Nautolan,Male,1.96,87.0,NaN,Black,Green,48.0,Glee Anselm,19.0,A Jedi Master known for his underwater combat ...
59,60,Savage Opress,Dathomirian,Male,2.18,100.0,NaN,Yellow,Pale,49.0,Dathomir,19.0,The brother of Darth Maul and a powerful Sith ...
61,62,Pong Krell,Besalisk,Male,2.50,300.0,NaN,Yellow,Green,52.0,Ojom,19.0,A Jedi Master who fell to the dark side.
65,66,Kallus,Human,Male,1.88,85.0,Blond,Blue,Light,40.0,Coruscant,NaN,An Imperial agent who defected to the Rebel Al...
66,67,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
72,73,Baze Malbus,Human,Male,1.85,95.0,Black,Brown,Light,52.0,Jedha,0.0,A former Guardian of the Whills and companion ...
76,77,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
79,80,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
85,86,Baze Malbus,Human,Male,1.85,95.0,Black,Brown,Light,52.0,Jedha,0.0,A former Guardian of the Whills and companion ...

### Exercise 7 - 💻 ✅

Hint: You can use isin() function to filter through a list: df_characters[df_characters["eye_color"].isin(["Blue","Brown"])]

Select characters whose **eye_color** is not either **Blue** or **Brown**, and whose **hair_color** is **Green**.

In [8]:
# option 1:
df_characters[(~df_characters['eye_color'].isin(['Blue','Brown'])) & (df_characters['hair_color']=='Green')]
# option 2:
condition = (~df_characters['eye_color'].isin(['Blue', 'Brown'])) & (df_characters['hair_color'] == 'Green')
df_characters[condition]
# option 3:
condition = ((df_characters['eye_color'] != 'Blue') & (df_characters['eye_color'] != 'Brown') & (df_characters['hair_color'] == 'Green'))
df_characters[condition]
# option 4:
df_characters.query("eye_color not in ['Blue','Brown'] and hair_color == 'Green'")
# option 5:
df_characters.loc[condition]

Empty DataFrame
Columns: [id, name, species, gender, height, weight, hair_color, eye_color, skin_color, year_born, homeworld, year_died, description]
Index: []

### Exercise 8 - 💻 ✅

Find characters who are taller than 180 cm, are not human, and do not weigh more than 100 kg.

In [10]:
# option 1:
df_characters[(df_characters['height']>1.8) & (df_characters['species']!='Human') & (df_characters['weight']<=100)]
# option 2:
df_characters[~(df_characters['height']<=1.8) & ~(df_characters['species']=='Human') & ~(df_characters['weight']>100)]
# option 3:
df_characters.query("height > 180 and species != 'human' and weight <= 100")
# option 4:
df_characters.loc[(df_characters['height']>1.8) & (df_characters['species']!='Human') & (df_characters['weight']<=100)]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52.0,Naboo,NaN,A clumsy Gungan who became a representative in...
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.
34,35,Bib Fortuna,Twi'lek,Male,1.93,65.0,NaN,Red,Pale,60.0,Ryloth,35.0,A majordomo for Jabba the Hutt.
43,44,Kit Fisto,Nautolan,Male,1.96,87.0,NaN,Black,Green,48.0,Glee Anselm,19.0,A Jedi Master known for his underwater combat ...
47,48,Plo Koon,Kel Dor,Male,1.88,80.0,NaN,Black,Orange,44.0,Dorin,19.0,A Jedi Master known for his unique mask.
50,51,Shaak Ti,Togruta,Female,1.87,68.0,NaN,Black,Red,43.0,Shili,NaN,A Jedi Master and member of the Jedi High Coun...
55,56,Ahsoka Tano,Togruta,Female,1.88,55.0,NaN,Blue,Orange,36.0,Shili,NaN,A former Jedi Padawan of Anakin Skywalker.
57,58,Cad Bane,Duros,Male,1.85,75.0,NaN,Red,Blue,62.0,Duro,NaN,A feared bounty hunter.
59,60,Savage Opress,Dathomirian,Male,2.18,100.0,NaN,Yellow,Pale,49.0,Dathomir,19.0,The brother of Darth Maul and a powerful Sith ...
66,67,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
79,80,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...

### Exercise 9 - 💻 ✅

Find characters who are either female and taller than 160 cm, OR male and taller than 190 cm.

In [16]:
# option 1:
df_characters[((df_characters['gender'] == 'Female') & (df_characters['height']>1.6)) | ((df_characters['gender'] == 'Male') & (df_characters['height']>1.9))]
# option 2:
df_characters.loc[((df_characters['gender'] == 'Female') & (df_characters['height'] > 1.6)) | ((df_characters['gender'] == 'Male') & (df_characters['height'] > 1.9))]
# option 3:
df_characters.query("(gender=='Female' and height >1.6) or (gender == 'Male' and height >1.9)")

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200.0,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
9,10,Padmé Amidala,Human,Female,1.65,45.0,Brown,Brown,Light,46.0,Naboo,19.0,The queen-turned-senator of Naboo and wife of ...
10,11,Qui-Gon Jinn,Human,Male,1.93,89.0,Brown,Blue,Light,92.0,Coruscant,32.0,A Jedi Master who discovered Anakin Skywalker.
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52.0,Naboo,NaN,A clumsy Gungan who became a representative in...
13,14,Count Dooku,Human,Male,1.93,80.0,White,Brown,Light,102.0,Serenno,19.0,"A former Jedi who became Darth Tyranus, a Sith..."
14,15,Rey,Human,Female,1.70,54.0,Brown,Hazel,Light,15.0,Jakku,NaN,The main protagonist of the sequel trilogy.
25,26,Rose Tico,Human,Female,1.68,57.0,Black,Brown,Light,11.0,Hays Minor,NaN,A mechanic in the Resistance.
26,27,Supreme Leader Snoke,Unknown,Male,2.18,100.0,NaN,Blue,Pale,50.0,Unknown,34.0,The Supreme Leader of the First Order.
28,29,Aayla Secura,Twi'lek,Female,1.78,55.0,Blue,Hazel,Blue,48.0,Ryloth,19.0,A Jedi Knight during the Clone Wars.
31,32,Bail Organa,Human,Male,1.91,86.0,Black,Brown,Light,67.0,Alderaan,0.0,A senator and adoptive father of Leia Organa.
32,33,Barriss Offee,Mirialan,Female,1.66,50.0,Black,Blue,Green,40.0,Mirial,19.0,A Jedi Padawan during the Clone Wars.
34,35,Bib Fortuna,Twi'lek,Male,1.93,65.0,NaN,Red,Pale,60.0,Ryloth,35.0,A majordomo for Jabba the Hutt.
36,37,Captain Phasma,Human,Female,2.00,75.0,Blonde,Blue,Light,15.0,Parnassos,35.0,A high-ranking officer in the First Order.
40,41,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
41,42,Jabba the Hutt,Hutt,Male,3.90,1358.0,NaN,Orange,Green,600.0,Nal Hutta,4.0,A notorious crime lord.
42,43,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
43,44,Kit Fisto,Nautolan,Male,1.96,87.0,NaN,Black,Green,48.0,Glee Anselm,19.0,A Jedi Master known for his underwater combat ...
45,46,Mon Mothma,Human,Female,1.70,55.0,Red,Blue,Light,48.0,Chandrila,NaN,A leader in the Rebel Alliance.
50,51,Shaak Ti,Togruta,Female,1.87,68.0,NaN,Black,Red,43.0,Shili,NaN,A Jedi Master and member of the Jedi High Coun...
51,52,Shmi Skywalker,Human,Female,1.65,55.0,Brown,Brown,Light,72.0,Tatooine,22.0,The mother of Anakin Skywalker.
54,55,Zam Wesell,Clawdite,Female,1.78,60.0,Brown,Yellow,Green,32.0,Zolan,22.0,A shape-shifting bounty hunter.
55,56,Ahsoka Tano,Togruta,Female,1.88,55.0,NaN,Blue,Orange,36.0,Shili,NaN,A former Jedi Padawan of Anakin Skywalker.
56,57,Asajj Ventress,Dathomirian,Female,1.70,55.0,NaN,Blue,Pale,57.0,Dathomir,19.0,A former Sith apprentice turned bounty hunter.
59,60,Savage Opress,Dathomirian,Male,2.18,100.0,NaN,Yellow,Pale,49.0,Dathomir,19.0,The brother of Darth Maul and a powerful Sith ...
61,62,Pong Krell,Besalisk,Male,2.50,300.0,NaN,Yellow,Green,52.0,Ojom,19.0,A Jedi Master who fell to the dark side.
62,63,Mother Talzin,Dathomirian,Female,1.70,55.0,Black,Green,Pale,100.0,Dathomir,19.0,A powerful witch and leader of the Nightsisters.
64,65,Sabine Wren,Human,Female,1.65,50.0,Varied,Brown,Light,21.0,Mandalore,NaN,A Mandalorian artist and warrior.
66,67,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
67,68,Jyn Erso,Human,Female,1.70,60.0,Brown,Green,Light,22.0,Vallt,0.0,The protagonist of Rogue One and a member of t...
75,76,Hera Syndulla,Twi'lek,Female,1.78,55.0,Green,Blue,Green,29.0,Ryloth,NaN,A skilled pilot and leader of the Ghost crew.
76,77,Kanan Jarrus,Human,Male,1.91,86.0,Brown,Blue,Light,32.0,Coruscant,2.0,A Jedi Knight and member of the Ghost crew.
78,79,Sabine Wren,Human,Female,1.65,50.0,Varied,Brown,Light,21.0,Mandalore,NaN,A Mandalorian artist and warrior.
79,80,Grand Admiral Thrawn,Chiss,Male,1.95,85.0,Blue-Black,Red,Blue,50.0,Csilla,NaN,A brilliant tactician and leader in the Imperi...
80,81,Jyn Erso,Human,Female,1.70,60.0,Brown,Green,Light,22.0,Vallt,0.0,The protagonist of Rogue One and a member of t...
90,91,Qi'ra,Human,Female,1.70,50.0,Brown,Brown,Light,21.0,Corellia,NaN,A member of the Crimson Dawn syndicate.
91,92,Enfys Nest,Human,Female,1.68,55.0,Red,Brown,Light,19.0,Unknown,NaN,A rebel and leader of the Cloud-Riders.
94,95,Val,Human,Female,1.75,55.0,Black,Brown,Dark,30.0,Unknown,10.0,A member of Beckett's crew.

### Exercise 10 - 💻 ✅

**Let's take a subset of the data**

In [11]:
df_droids = df_characters[df_characters["species"] == "Droid"][["name","homeworld","description"]]

There are 4 droids

In [92]:
df_droids

     name homeworld                                        description
18   BB-8       NaN                       A spherical astromech droid.
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 1**: What is happening in the code below? Which lines are selected and why?

Answer:
[False,True,True,True] are the conditions for selecting ROWs:
- Row 1: False --> not selected --> not shown
- Row 2: True --> selected --> shown
- Row 3: True --> selected --> shown
- Row 4: True --> selected --> shown

In [93]:
df_droids[[False,True,True,True]]

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 2**: Why does this code produce the similar output?

ANSWER: df_droids["name"].str.len() == 5: means selecting ROWs with names which have string length of 5.
- Row 1 name's length is only 4: --> not selected --> not shown.
- The remaining Rows have names' length of 5: --> selected and shown.

In [94]:
df_droids[df_droids["name"].str.len() == 5]

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

### Bonus exercise 🐇🕳️

First make sure **numpy** is installed

In [53]:
!pip install numpy

Requirement already satisfied: numpy in /home/harttu/venv/lib/python3.12/site-packages (2.4.3)

In [17]:
import numpy as np

There is a problem in this code. Google/Use LLM to find out why it doesn't work.

In [85]:
df_droids[([True,False,True,False]) & ([False,True,False,False])]

TypeError: unsupported operand type(s) for &: 'list' and 'list'

However this works

In [86]:
np.array([True, False, True, False]) & np.array([False, True, False, False])

array([False, False, False, False])

**Question 1**: Use that syntax to make the original failing df_droid selection work?

In [95]:
df_droids[np.array([True, False, True, False]) & np.array([False, True, False, False])]

Empty DataFrame
Columns: [name, homeworld, description]
Index: []

**Question 2**: What does this tell about inner working of pandas? Does it work with numpy or basic python under the hood?

- This shows Pandas is built on Numpy (works with Numpy under the hood)
- Core structures of Pandas such as Series and DataFrame are actually Arrays from Numpy (numpy.ndarray).
- Therefore, the operations of Pandas inherit operation machanism of Numpy (veectorized, element-wise operations), and not as in normal List by Python.