# Joining tables with `merge`

`DataFrame.merge` attaches columns from a second table onto the first.
`how` decides which rows stay. The default is `"inner"`.

| Join | Rows that stay |
|---|---|
| inner | keys in both tables |
| left | every row from the left table |
| right | every row from the right table |
| outer | keys from either table |
| cross | every left row paired with every right row |
| semi | left rows whose key is in the right table, left columns only |
| anti | left rows whose key is missing from the right table |

Pandas has no `how="semi"`. We will do a workaround for that.

## How to work through it

Run the cells from the top down. Example cells are filled in.
Each join ends with one medium exercise. Write code in the empty cell.
When the question asks why, answer in a comment.

Put your finished notebook in `week-(current week)/student_work/`.

---
## 1. The two tables

The shared column is `customer_id`.

- Customer 101 has one order.
- Customer 102 has two orders, coffee and biscuit.
- Customer 104 ordered cake, and is missing from `customers`.
- Customer 103 lives in Turku and has no order.

In [1]:
import pandas as pd

# %pip install pandas

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4],
    "customer_id": [101, 102, 104, 102],
    "item": ["tea", "coffee", "cake", "biscuit"],
})

customers = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "city": ["Helsinki", "Tampere", "Turku"],
})

display(orders)
display(customers)

   order_id  customer_id     item
0         1          101      tea
1         2          102   coffee
2         3          104     cake
3         4          102  biscuit

   customer_id      city
0          101  Helsinki
1          102   Tampere
2          103     Turku

---
## 2. Inner join

An inner join keeps a row when `customer_id` is in both tables.
Order 3 drops out, because 104 is not in `customers`.
Customer 102 has two orders, so Tampere is attached to both.

In [ ]:
orders.merge(customers, on="customer_id", how="inner")

### Exercise 2

Which `order_id` values are in the result?
Which order disappears, and why?

---
## 3. Left join

A left join keeps every row of `orders`.
The city is filled in when that customer exists.
The cake order stays, and its city is missing.

In [ ]:
orders.merge(customers, on="customer_id", how="left")

### Exercise 3 

Which item has a missing city? Is that order kept?

---
## 4. Right join

A right join keeps every row of `customers`.
Turku stays, with no order. The cake order is dropped.
`order_id` prints as `1.0` where an order exists, and `NaN` for Turku.

In [ ]:
orders.merge(customers, on="customer_id", how="right")

### Exercise 4

Which city has a missing item? Why is the cake order absent?

---
## 5. Outer join

An outer join keeps a row when the key is in `orders`, in `customers`, or in both.
Cake stays, with a missing city. Turku stays, with a missing order.
In pandas 3 the unmatched rows sit at the end.

In [ ]:
orders.merge(customers, on="customer_id", how="outer")

### Exercise 5

How many rows are in the result?
Which `customer_id` has no city, and which `customer_id` has no item?

---
## 6. Cross join

A cross join pairs every order with every customer. It takes no key.
Both tables have a column named `customer_id`, so the result calls them
`customer_id_x` and `customer_id_y`.
Four orders and three customers give 4 × 3 = 12 rows.

In [ ]:
orders.merge(customers, how="cross")

### Exercise 6

How many rows does the cross join return?
Why are there two customer-id columns?

---
## 7. Semi join

A semi join keeps left rows whose key is in the right table, and it keeps only the left columns.
Pass the right table as the key column alone, then inner-merge.
The matching orders stay. The `city` column does not come along.

In [ ]:
orders.merge(customers[["customer_id"]], on="customer_id", how="inner")

### Exercise 7

Which `order_id` values remain?
Which column from `customers` is absent, and why?

---
## 8. Anti join

An anti join keeps left rows whose key is missing from the right table.

In [ ]:
orders.merge(customers, on="customer_id", how="left_anti", indicator=True )

### Exercise 8

What would be the output of `how = "right_anti"` and why? What does the `indicator=True` do?