# Exercise 5 - Stack It! Merge It!

In [3]:
import pandas as pd

df_population = pd.DataFrame({
    "country": ["Finland", "Japan", "Bhutan", "Tuvalu"],
    "population": [5_620_000, 123_975_000, 790_000, 10_000]
})

df_gdp = pd.DataFrame({
    "country": ["Finland", "Japan", "Bhutan", "Tuvalu"],
    "gdp": [300, 4_200, 3.0, 0.06]
})

df_population 
df_gdp 

# Now run:pd.merge(df_population, df_gdp, on = "country")
pd.merge(df_population, df_gdp, on = "country")

# Write in simple terms what did you get? And how does this differ from pd.concat we used in other exercises?
'''
- We get a single DataFrame where the 2 columns 'country' are combined into a single column,
and 'gdp' column is added to the right side of the 'population' column.
- The 2 DataFrames are combined horizontally. 
- The indices are unique, in the order from 0 to 3.
- For merge: there must be a common 'country' column on both DataFrames!!
- Whereas, pd.concat will combine the 2 DataFrames vertically or horizontally depending on the variable 'axis = 0' or 'axis = 1'.
- Even if the pd.concat stacks the 2 tables horizontally (axis = 1), the 'country' will be added 2 times. 
Therefore, there will be 2 'country' variables/columns if we use 'pd.concat'.
- If the pd.concat stacks the 2 tables vertically (axis = 0), the country names will be added repeatedly in new rows.
The values for 'population' and 'gdp' will be either NaN or original numbers depending which original DataFrame they belonged to.
'''

pd.concat([df_population,df_gdp],axis=0)

   country   population      gdp
0  Finland    5620000.0      NaN
1    Japan  123975000.0      NaN
2   Bhutan     790000.0      NaN
3   Tuvalu      10000.0      NaN
0  Finland          NaN   300.00
1    Japan          NaN  4200.00
2   Bhutan          NaN     3.00
3   Tuvalu          NaN     0.06

In [4]:
import pandas as pd

df1 = pd.DataFrame({'firstname': ['The', 'Oanh','Minh','Linh'],
                    'middlename': ['Cao','Thi Kieu','Hoang Gia','Hoang Gia'],
                    'lastname': ['Bui', 'Hoang','Bui','Bui'],
                    'mobile': ['0967883765','0987882365','0978654324','0968766544'],
                    'email':['buicaothe@gmail.com','kieoaunh@gmail.com','giaminh@gmail.com','gialinh@gmail.com']
                    })

df2 = pd.DataFrame({'occupation': ['Engineer', 'Teacher','Student','Student'],
                    'birthyear': [1981,1982,2010,2013],
                    'age': [45,44,16,13],
                    'height': [1.70, 1.56,1.69,1.58],
                    'weight': [65,48,68,40],
                    'firstname': ['The', 'Oanh','Minh','Linh'],
                    })


pd.concat([df1,df2],axis=1)
pd.merge(df1, df2, on = 'firstname') # must have 'firstname' on both DataFrames!!

,firstname,middlename,lastname,mobile,email,occupation,birthyear,age,height,weight
0,The,Cao,Bui,0967883765,buicaothe@gmail.com,Engineer,1981,45,1.70,65
1,Oanh,Thi Kieu,Hoang,0987882365,kieoaunh@gmail.com,Teacher,1982,44,1.56,48
2,Minh,Hoang Gia,Bui,0978654324,giaminh@gmail.com,Student,2010,16,1.69,68
3,Linh,Hoang Gia,Bui,0968766544,gialinh@gmail.com,Student,2013,13,1.58,40

In [33]:
df3 = pd.DataFrame({"address":['same house','same house','same house','same house'],
                    'firstname': ['The', 'Oanh','Minh','Linh']})
df3

      address firstname
0  same house       The
1  same house      Oanh
2  same house      Minh
3  same house      Linh

In [ ]:
concat = pd.concat([df1,df3]) # concat works with more than 2 dataframes at the same time,
b
concat

  firstname middlename lastname      mobile                email     address
0       The        Cao      Bui  0967883765  buicaothe@gmail.com         NaN
1      Oanh   Thi Kieu    Hoang  0987882365   kieoaunh@gmail.com         NaN
2      Minh  Hoang Gia      Bui  0978654324    giaminh@gmail.com         NaN
3      Linh  Hoang Gia      Bui  0968766544    gialinh@gmail.com         NaN
0       The        NaN      NaN         NaN                  NaN  same house
1      Oanh        NaN      NaN         NaN                  NaN  same house
2      Minh        NaN      NaN         NaN                  NaN  same house
3      Linh        NaN      NaN         NaN                  NaN  same house

In [ ]:
a = pd.merge(df1,df2, on= 'firstname')
b = pd.merge(a,df3, on= 'firstname') # merge only works with maximum 2 dataframes in one shot
b

,firstname,middlename,lastname,mobile,email,occupation,birthyear,age,height,weight,address
0,The,Cao,Bui,0967883765,buicaothe@gmail.com,Engineer,1981,45,1.70,65,same house
1,Oanh,Thi Kieu,Hoang,0987882365,kieoaunh@gmail.com,Teacher,1982,44,1.56,48,same house
2,Minh,Hoang Gia,Bui,0978654324,giaminh@gmail.com,Student,2010,16,1.69,68,same house
3,Linh,Hoang Gia,Bui,0968766544,gialinh@gmail.com,Student,2013,13,1.58,40,same house