# Exercise 2 - Learn Concat

In [3]:
import pandas as pd

In [10]:
df1 = pd.DataFrame({
    "country": ["Belize", "Liechtenstein", "Bhutan"],
    "population": [417_000, 40_000, 790_000]
})

df2 = pd.DataFrame({
    "country": ["Suriname", "São Tomé and Príncipe", "Tuvalu"],
    "population": [630_000, 240_000, 10_000]
})
print('- DataFrame 1 (df1):\n',df1)
print('- DataFrame 2 (df1):\n',df2)
df1

- DataFrame 1 (df1):
          country  population
0         Belize      417000
1  Liechtenstein       40000
2         Bhutan      790000
- DataFrame 2 (df1):
                  country  population
0               Suriname      630000
1  São Tomé and Príncipe      240000
2                 Tuvalu       10000

         country  population
0         Belize      417000
1  Liechtenstein       40000
2         Bhutan      790000

In [12]:
# --------------------------------------------------------------
# A. Use pandas.concat to put them in one data frame called df.
# --------------------------------------------------------------
df = pd.concat([df1,df2])
df

                 country  population
0                 Belize      417000
1          Liechtenstein       40000
2                 Bhutan      790000
0               Suriname      630000
1  São Tomé and Príncipe      240000
2                 Tuvalu       10000

In [14]:
# --------------------------------------------------------------
# B. Use sort_values()-method to sort DataFrame df by population in ascending order.
# --------------------------------------------------------------
sort = df.sort_values('population')
sort

                 country  population
2                 Tuvalu       10000
1          Liechtenstein       40000
1  São Tomé and Príncipe      240000
0                 Belize      417000
0               Suriname      630000
2                 Bhutan      790000

In [17]:
# --------------------------------------------------------------
# C. What is the difference between pandas.concat([df1,df2], axis = 0) and pandas.concat([df1,df2], axis = 1)
# --------------------------------------------------------------
'''
- pandas.concat([df1,df2], axis = 0): APPEND ROWS OF DATAFRAMES (VERTICALLY)
- pandas.concat([df1,df2], axis = 1): APPEND COLUMNS OF DATAFRAMES (HORIZONTALLY)
'''

df_axis1 = pd.concat([df1,df2], axis = 1)
df_axis1

         country  population                country  population
0         Belize      417000               Suriname      630000
1  Liechtenstein       40000  São Tomé and Príncipe      240000
2         Bhutan      790000                 Tuvalu       10000

In [24]:
# --------------------------------------------------------------
# D. What does df.loc[0] now return? 
# --------------------------------------------------------------
df.loc[0]
#type(df.loc[0])
# Return a DataFrame with 2 values index[0] from 2 original dataframe (df1,df2)

    country  population
0    Belize      417000
0  Suriname      630000