# Exercise 4 - Explore the Combined Data

In [1]:
import pandas as pd

In [7]:
df1 = pd.DataFrame({
    "country": ["Belize", "Liechtenstein", "Bhutan"],
    "population": [417_000, 40_000, 790_000]
})

df2 = pd.DataFrame({
    "country": ["Suriname", "São Tomé and Príncipe", "Tuvalu"],
    "population": [630_000, 240_000, 10_000]
})

df1
df2

                 country  population
0               Suriname      630000
1  São Tomé and Príncipe      240000
2                 Tuvalu       10000

In [15]:
df = pd.concat([df1,df2],ignore_index=True)
df

                 country  population
0                 Belize      417000
1          Liechtenstein       40000
2                 Bhutan      790000
3               Suriname      630000
4  São Tomé and Príncipe      240000
5                 Tuvalu       10000

In [17]:
# Stack with pandas.concat and apply the following functions to _population_ column.
print('- Average/Mean value:',df.population.mean()) # The average population across all countries
print('- Sum value:',df.population.sum()) # The total population of all countries combined
print('- Minimum value:',df.population.min()) # The smallest population among the countries
print('- Maximum value:',df.population.max()) # The biggest population among the countries
print('- Count value:',df.population.count()) # The number of non-empty data rows/countries
print('- Median value:',df.population.median()) # The middle value when populations are sorted in order
print('- Standard Deviation value:',df.population.std()) # Standard deviation: shows how spread out the values are from the average
print('- Variance value:',df.population.var()) # Variance: measures the degree of spread in the data (squared standard deviation)

- Average/Mean value: 354500.0
- Sum value: 2127000
- Minimum value: 10000
- Maximum value: 790000
- Count value: 6
- Median value: 328500.0
- Standard Deviation value: 316280.72973230603
- Variance value: 100033500000.0