# Homework 1 (Hard deadline: 18.10.2026 22:00:)


- Use file Activities2018-2025.csv
- Read it first in Pandas DataFrame and then complete the tasks.
- Remember to comment your code, good policy is to have at least a short comment in every code cell.
- Add code cells when necessary.
- Good policy is to do one or few related operations in one code cell (e.g. read csv and check how it looks like in one cell and then e.g. df.info() in another etc.).


### Use of AI: can be used, but must be reported.
### AI shall not be used to complete the whole assignment.

In [1]:
# Take necessary libraries in use
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Task 1: Data reading and checking (1 point)
- Read data (Activities2018-2025.csv) to a Pandas DataFrame whose name is df.
- Check that data looks ok.
- Show number of rows and columns.
- Show key data measures (mean, std, median, ...) for the DataFrame.
- Show also info about DataFrame.
- Check if there are missing values.

In [4]:
# Read data (Activities2018-2025.csv) to a Pandas DataFrame whose name is df.
df = pd.read_csv('Activities2018-2025.csv') # create a data frame named 'df' by read the csv file Activities2018-2025.
df.head()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Steps,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Walking,2025-09-11 18:31:24,False,Rusko Walking,"3,92",244,01:00:06,93,128,"1,4",...,5.574,"23,0",No,01:00:06,1,"27,0",00:57:51,01:00:06,57,71
1,Cycling,2025-09-10 18:49:40,False,Rusko Cycling,"10,60",254,00:42:59,111,142,"2,0",...,--,"20,0",No,00:19:25,2,"28,0",00:34:06,01:12:23,-36,8
2,Other,2025-09-08 15:47:11,False,Salibandy,"0,00",580,01:28:15,117,169,"3,1",...,--,"27,0",No,01:28:15,1,"32,0",00:00:00,01:28:15,-66,-60
3,Walking,2025-09-08 07:25:35,False,Rusko Walking,"3,48",373,00:41:03,133,183,"3,8",...,4.480,"21,0",No,00:41:03,1,"29,0",00:40:20,00:41:03,-40,-21
4,Cycling,2025-09-06 11:45:12,False,Rusko Cycling,"21,08",331,01:07:16,104,141,"2,0",...,--,"25,0",No,00:18:54,3,"30,0",01:04:50,01:28:43,-34,-5

In [6]:
# Check that data looks ok.
df # print all rows and all coloumns of the DataFrame
df.head() # print 5 rows and all columns of the DataFrame

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Steps,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Walking,2025-09-11 18:31:24,False,Rusko Walking,"3,92",244,01:00:06,93,128,"1,4",...,5.574,"23,0",No,01:00:06,1,"27,0",00:57:51,01:00:06,57,71
1,Cycling,2025-09-10 18:49:40,False,Rusko Cycling,"10,60",254,00:42:59,111,142,"2,0",...,--,"20,0",No,00:19:25,2,"28,0",00:34:06,01:12:23,-36,8
2,Other,2025-09-08 15:47:11,False,Salibandy,"0,00",580,01:28:15,117,169,"3,1",...,--,"27,0",No,01:28:15,1,"32,0",00:00:00,01:28:15,-66,-60
3,Walking,2025-09-08 07:25:35,False,Rusko Walking,"3,48",373,00:41:03,133,183,"3,8",...,4.480,"21,0",No,00:41:03,1,"29,0",00:40:20,00:41:03,-40,-21
4,Cycling,2025-09-06 11:45:12,False,Rusko Cycling,"21,08",331,01:07:16,104,141,"2,0",...,--,"25,0",No,00:18:54,3,"30,0",01:04:50,01:28:43,-34,-5

In [19]:
# Show number of rows and columns.
df.columns # show all columns names only
# df.info() # show all DataFrame information, including number of rows and columns.
print('- Number of rows and columns: ', df.shape) # shown number of rows and columns: (rows, columns)

print('- Number of rows   : ', df.shape[0]) # show number of rows only
print('- Number of columns: ', df.shape[1]) # show number of columns only
df.shape[1]

# check the type of (df.shape):
type(df.shape) # this is a tuple

- Number of rows and columns:  (1560, 33)
- Number of rows   :  1560
- Number of columns:  33

tuple

In [22]:
# Show key data measures (mean, std, median, ...) for the DataFrame.
df.describe()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Steps,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
count,1560,1560,1560,1560,1560,1560,1560,1560,1560,1560,...,1560,1560,1560,1560,1560,1560,1560,1560,1560,1560
unique,22,1560,2,220,729,628,1323,86,113,41,...,723,30,1,1047,13,27,1080,1324,386,381
top,Walking,2025-09-11 18:31:24,False,Salibandy,"0,00",172,00:37:24,--,--,"1,1",...,--,"22,0",No,--:--:--,1,"28,0",00:00:00,01:02:30,--,--
freq,385,1,1555,199,258,10,3,65,65,257,...,744,115,1560,372,1052,309,285,4,94,93

In [ ]:
# Show also info about DataFrame.
# Check if there are missing values.

## Task 2: Explain the code (add explanation as comments to the code cells) (1 point)
- Do not change the code, only add comments.

In [ ]:
# Explain this code

cols = df.columns
print(cols)

In [ ]:
# Explain this code

for col in cols:
    df[col] = df[col].apply(lambda x: x.replace(',', '.') if isinstance(x, str) else x)

df.head(10)

### Let's do some conversion here.

In [ ]:
# Convert data types to numeric in selected columns.
# Do not change this code.
cols = ['Distance', 'Calories', 'Avg HR', 'Max HR', 'Aerobic TE', 'Avg Cadence', 'Max Cadence',
       'Avg Pace', 'Best Pace', 'Total Ascent', 'Total Descent',
       'Avg Stride Length', 'Avg Cadence.1', 'Max Cadence.1',
       'Training Stress Score®', 'Total Strokes', 'Avg. Swolf',
       'Avg Stroke Rate', 'Steps', 'Min Temp', 'Decompression',
       'Number of Laps', 'Max Temp', 'Min Elevation', 'Max Elevation']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df.info()

## Task 3: Why is there suddenly now a lot of missing values? (1 point)

Your answer here:

## Task 4: Remove all the activities where the distance is less than 5 (km) (1 point)

## Task 5: Convert "Date" column into datetime format and check with info() what happened (1 point)

## Task 6: Remove columns that do not seem to be useful (1 point)
- Drop columns containing a lot of missing values
- Drop columns that seem irrelevant
- Keep at least 10 variables that you like to study (keep both qualitative and quantitative columns)

## Tasks 7-10: Visualize data (4 points, 1 per plot)
- Create at least 4 different figures using the data (one histogram, one bar plot, one box plot and one scatter plot (where data is separated by activity type)). Use approrpriate titles, axis names, labels, colors, etc. (= plots are readable and understandable).
- Use Matplotlib and Seaborn.
- Find out first, which type of data is best presented with above mentioned plots!

## Task: AI statement (mandatory, missing AI statement (if AI used) is considered fraud)
- Describe here, how did you use AI in this assignment
- Describe also, if you did not use AI in this assignment

## Task: Self assessment (mandatory, missing self assessment causes -1 point)
- How many points would you give yourself? ANSWER HERE:
- You get a point if you have completed the task according to instructions.
- How many tasks you did not complete? ANSWER HERE:

## Homework return (mandatory)
- File > Save and Export Notebook As > HTML
- Then take a look the produced HTML that it looks ok and readable (= it looks like this Jupyter notebook looks, so no html source code etc. shall be visible)
- Return to Itslearning, only the html document is returned, *not the .ipynb