# Week 5 — `min`, `max`, and `concat`

Each Maddison file in `week-05/materials/maddison_by_country/` is one entity, with columns `Entity`, `Code`, `Year`, and `GDP`.

`.min()` and `.max()` reduce a column to one value. `pd.concat` stacks those files back into one table.

Run this notebook from `introduction-to-data-engineering`, from `week-05/materials`, or from `week-05/student_work`.

## Find the folder

In [1]:
from pathlib import Path
import pandas as pd

def find_existing(candidates):
    for path in candidates:
        if path.exists():
            return path
    searched = "\n".join(str(path) for path in candidates)
    raise FileNotFoundError(
        "Could not find the Maddison folder. Looked in:\n" + searched
    )


cwd = Path.cwd()
maddison_dir = find_existing(
    [
        cwd / "maddison_by_country",
        cwd / "materials/maddison_by_country",
        cwd / "week-05/materials/maddison_by_country",
        cwd / "../materials/maddison_by_country",
        cwd / "week-03/materials/maddison_by_country",
        cwd / "../../week-03/materials/maddison_by_country",
    ]
)
maddison_dir

WindowsPath('d:/PYTHON/DATA ENGINEERING/Week 05/maddison_by_country')

## One file: Finland

`.min()` is the smallest value in that column. `.max()` is the largest. `Year.min()` is the earliest year in the file. `Year.max()` is the latest year.

In [2]:
finland = pd.read_csv(maddison_dir / "Finland.csv")
finland.head(3)

    Entity Code  Year         GDP  GDP (Annotations)
0  Finland  FIN  1600   476400000                NaN
1  Finland  FIN  1700   532400000                NaN
2  Finland  FIN  1820  1534897000                NaN

In [3]:
finland["Year"].min(), finland["Year"].max()

(np.int64(1600), np.int64(2022))

In [4]:
finland["GDP"].min(), finland["GDP"].max()

(np.int64(476400000), np.int64(226154847456))

The number alone leaves out the year it belongs to. `.idxmin()` is the row label where GDP is smallest. `.loc` reads that row. `.idxmax()` does the same for the largest GDP.

In [ ]:
a = finland.loc[finland["GDP"].idxmin(), ["Entity", "Year", "GDP"]] # return a Series with columns name as Label-based Index. Retun the Min GDP of Finland.
# Show the row with filter columns Entity, Year and GDP
print(a)
type(a)

Entity      Finland
Year           1600
GDP       476400000
Name: 0, dtype: object

pandas.Series

In [ ]:
finland.loc[finland["GDP"].idxmax(), ["Entity", "Year", "GDP"]] # return tthe ROW INDEX (not a Label) of the max GDP of Finland.
# show the rows with filter columns "Entity","Year" and "GDP"

Entity         Finland
Year              2022
GDP       226154847456
Name: 166, dtype: object

Finland's file runs from 1600 to 2022. The smallest GDP is in 1600, and the largest GDP is in 2022. On this file the two year questions happen to land on the same rows.

## The two year questions on Afghanistan

`Year.min()` answers "what is the earliest year in these rows?".

`df.loc[df["GDP"].idxmin(), "Year"]` answers "in which year is GDP smallest?".

On Afghanistan those years differ. Run both before you decide which question you meant.

In [100]:
afghanistan = pd.read_csv(maddison_dir / "Afghanistan.csv") # read the file csv from the saved directory maddison_dir
afghanistan["Year"].min(), afghanistan["Year"].max() # ealiest year, lastest year

(np.int64(1950), np.int64(2022))

In [ ]:
afghanistan.loc[afghanistan["GDP"].idxmin(), ["Entity", "Year", "GDP"]] # return datafarme with Row Index (not a Label) of min GDP of Afga. 
# show only columns "Entity", "Year" and "GDP"

Entity    Afghanistan
Year             1994
GDP        7919856426
Name: 44, dtype: object

In [ ]:
afghanistan.loc[afghanistan["GDP"].idxmax(), ["Entity", "Year", "GDP"]] # return datafarme with Row Index (not a Label) of max GDP of Afga. 
# show only columns "Entity", "Year" and "GDP"

Entity    Afghanistan
Year             2019
GDP       73085701943
Name: 69, dtype: object

The Afghanistan file starts in 1950 and ends in 2022. The smallest GDP is in 1994. The largest GDP is in 2019.

## Stack two files with `concat`

Build a list of DataFrames, then stack them. `ignore_index=True` writes a new row index. The row count equals the sum of the two files.

In [10]:
finland = pd.read_csv(maddison_dir / "Finland.csv")
sweden = pd.read_csv(maddison_dir / "Sweden.csv")
frames = [finland, sweden]
two_countries = pd.concat(frames, ignore_index=True)
len(finland), len(sweden), len(two_countries)

(167, 206, 373)

In [11]:
len(two_countries) == len(finland) + len(sweden)

True

In [12]:
two_countries["Entity"].unique() # in cloumn Entity, find the unique items --> a list (string array) and the length of the array

<StringArray>
['Finland', 'Sweden']
Length: 2, dtype: str

## In depth: stack every file

The loop reads each CSV into a list. `concat` stacks the list. One entity per file means `nunique()` matches the number of files.

Compare Finland inside the stacked table with `Finland.csv` on `Entity`, `Year`, and `GDP`.

In [13]:
all_frames = []
for path in sorted(maddison_dir.glob("*.csv")):
    all_frames.append(pd.read_csv(path))

df = pd.concat(all_frames, ignore_index=True)
len(all_frames), df["Entity"].nunique(), len(df) # number of (n)unique = integer
# len(all_frames) = df["Entity"].nunique(): number of unique items = length of the List of DataFrames

(178, 178, 16143)

In [14]:
len(df) == sum(len(frame) for frame in all_frames)

True

In [15]:
columns = ["Entity", "Year", "GDP"] # make a list of 3 column names
from_file = finland[columns].reset_index(drop=True) # "finland" là file gốc ở các bước đầu: lấy 3 cột
# reset_index(drop=True): đánh số lại index từ 0, bỏ qua index cũ.
from_all = df.loc[df["Entity"] == "Finland", columns].reset_index(drop=True)
# lọc ra 3 cột của hàng Finland từ file được concat. đánh số index lại từ 0, bỏ qua index cũ.
# các bước reset index là để 2 bảng có index giống nhau để dễ so sánh.
from_file.equals(from_all) # kiểm tra xem "from_file" = "from_all" hay không?
# Kết quả trả về True chứng minh rằng quá trình ghép nối (pd.concat) toàn bộ các tệp không làm sai lệch hay mất mát dữ liệu của Phần Lan.

True

## Practice

1. Read `Sweden.csv`. Report the earliest year, the latest year, the smallest GDP, the largest GDP, and the year of the smallest GDP.
2. You already stacked Finland and Sweden. What is `len(two_countries)`, and which two names are in `Entity`?
3. From the full table `df`, show the Afghanistan row where GDP is largest. Keep `Entity`, `Year`, and `GDP`.

### 1. Read `Sweden.csv`. Report the earliest year, the latest year, the smallest GDP, the largest GDP, and the year of the smallest GDP.

In [ ]:
# Read `Sweden.csv`:
sweden = pd.read_csv(maddison_dir / "Sweden.csv") # read Sweden DataFrame from maddison_dir folder saved earlier.
sweden.head(2) # print 2 row for checking

   Entity Code  Year        GDP  GDP (Annotations)
0  Sweden  SWE  1500  968000000                NaN
1  Sweden  SWE  1600  956080000                NaN

In [ ]:
# Report the earliest year, the latest year:
sw_minyear = sweden['Year'].min() # return the earliest year from the Sweden DataFrame
sw_maxyear = sweden['Year'].max() # return the latest year from the Swenden DataFrame
print('- The earliest year from the Sweden DataFrame:',sw_minyear)
print('- The latest year from the Sweden DataFrame  :',sw_maxyear)

# Smallest GDP, the largest GDP:
mingdp = sweden['GDP'].min()
maxgdp = sweden['GDP'].max()
print('- The min GDP from the Sweden DataFrame:',mingdp)
print('- The max GDP from the Sweden DataFrame:',maxgdp)

# The year of the smallest GDP:
year_of_mingdp = sweden.loc[sweden['GDP'] == mingdp]['Year']  # return a pandas Series
year_of_mingdp = sweden.loc[sweden['GDP'] == mingdp,['Year']] # return a pandas Series
year_of_mingdp = sweden[sweden['GDP'] == mingdp][['Year']]    # return a pandas Series
year_of_mingdp = sweden.loc[sweden["GDP"].idxmin(), "Year"]   # return the integer value. sweden["GDP"].idxmin(): return an Index (not the Label)
year_of_mingdp = sweden.at[sweden["GDP"].idxmin(), "Year"]    # return the integer value. sweden["GDP"].idxmin(): return an Index (not the Label)
print('- The Year of Min GDP from the Sweden DataFrame:',year_of_mingdp)

# check type:
print(type(sweden.loc[sweden['GDP'] == mingdp]['Year']))
print(type(sweden.loc[sweden["GDP"].idxmin(), "Year"]))

- The earliest year from the Sweden DataFrame: 1500
- The latest year from the Sweden DataFrame  : 2022
- The min GDP from the Sweden DataFrame: 956080000
- The max GDP from the Sweden DataFrame: 494214521158
- The Year of Min GDP from the Sweden DataFrame: 1600
<class 'pandas.Series'>
<class 'numpy.int64'>

### 2. You already stacked Finland and Sweden. What is `len(two_countries)`, and which two names are in `Entity`?

In [55]:
print('- The 2 country DataFrame:\n',two_countries.head(3))
print('- Length of 2 countries:',len(two_countries))

unique_names = two_countries['Entity'].unique()
print('- The 2 unique names:\n',unique_names)

- The 2 country DataFrame:
     Entity Code  Year         GDP  GDP (Annotations)
0  Finland  FIN  1600   476400000                NaN
1  Finland  FIN  1700   532400000                NaN
2  Finland  FIN  1820  1534897000                NaN
- Length of 2 countries: 373
- The 2 unique names:
 <StringArray>
['Finland', 'Sweden']
Length: 2, dtype: str

### 3. From the full table `df`, show the Afghanistan row where GDP is largest. Keep `Entity`, `Year`, and `GDP`.

In [ ]:
df.head()

        Entity Code  Year          GDP GDP (Annotations)
0  Afghanistan  AFG  1950   9421400000               NaN
1  Afghanistan  AFG  1951   9692280000               NaN
2  Afghanistan  AFG  1952  10017325000               NaN
3  Afghanistan  AFG  1953  10630520000               NaN
4  Afghanistan  AFG  1954  10866360000               NaN

In [ ]:
# largest GDP:
# OPTION 1:
print('--- OPTION 1 ---')
max_gdp = df[df['Entity'] == 'Afghanistan']['GDP'].max()
print('- The largest GDP of Afghanistan:',max_gdp)
row = df.loc[df['GDP']==max_gdp,['Entity','Year','GDP']] # return a DataFrame
row = df[df['GDP']==max_gdp][['Entity','Year','GDP']]    # return a DataFrame
print('- The Afghanistan row where GDP is largest:\n',row)

# check type:
print(type(df.loc[df['GDP']==max_gdp,['Entity','Year','GDP']]))
print(type(df[df['GDP']==max_gdp][['Entity','Year','GDP']]))

# OPTION 2:
print('--- OPTION 2 ---')
afhga = df.loc[df["Entity"]=='Afghanistan'][['Entity','Year','GDP']] # return a DataFrame
row2 = afhga.loc[afhga['GDP'].idxmax()]                         # return a pandas Series
row2 = afhga.loc[afhga['GDP'].idxmax(),['Entity','Year','GDP']] # return a pandas Series

print('- The Afghanistan row where GDP is largest:\n',row2)

# check type:
print(type(row2))

--- OPTION 1 ---
- The largest GDP of Afghanistan: 73085701943
- The Afghanistan row where GDP is largest:
          Entity  Year          GDP
69  Afghanistan  2019  73085701943
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
--- OPTION 2 ---
- The Afghanistan row where GDP is largest:
 Entity    Afghanistan
Year             2019
GDP       73085701943
Name: 69, dtype: object
<class 'pandas.Series'>

## Quiz

**1.** What does `finland["Year"].min()` return?

- A) The whole first row
- B) The earliest year in that column --> CHECK
- C) The year in which GDP is smallest
- D) The number of rows

**2.** Which line returns the year in which GDP is smallest?

- A) `df["Year"].min()`
- B) `df["GDP"].min()`
- C) `df.loc[df["GDP"].idxmin(), "Year"]`  --> CHECK
- D) `df["Year"].max()`

**3.** `pd.concat([finland, sweden], ignore_index=True)` produces a table whose row count is:

- A) The larger of the two files
- B) The sum of the two files' row counts  --> CHECK
- C) The number of columns
- D) One row per year that appears in both files

**4.** On Afghanistan, `Year.min()` is 1950. The year of the smallest GDP is:

- A) 1950
- B) 1994 --> CHECK
- C) 2019
- D) 2022

## Answer key

For the instructor. Remove this section before sharing the notebook if the quiz should be unseen.

**Quiz:** 1 B, 2 C, 3 B, 4 B. The largest Afghanistan GDP is in 2019 (option C is the trap).

**Practice:**

1. Sweden: earliest year 1500, latest year 2022, smallest GDP 956080000 in 1600, largest GDP 494214521158 in 2022.
2. `len(two_countries)` is 373 (167 + 206). The names are Finland and Sweden.
3. Afghanistan, year 2019, GDP 73085701943.

```python
sweden["Year"].min(), sweden["Year"].max()
sweden["GDP"].min(), sweden["GDP"].max()
sweden.loc[sweden["GDP"].idxmin(), ["Entity", "Year", "GDP"]]
```

Filter first, then `idxmax` on that table:

```python
afghanistan_rows = df[df["Entity"] == "Afghanistan"]
afghanistan_rows.loc[
    afghanistan_rows["GDP"].idxmax(), ["Entity", "Year", "GDP"]
]
```