# Week 5 — `groupby` and `merge`

`groupby` splits a table, computes something inside each group, and stacks the results. `merge` lines up two tables that share a key, and places their columns side by side.

The first groups are a four-row table you can check by eye. Then three Maddison files. The merge examples start with two tiny tables and end with a case where repeated keys multiply rows.

Run this notebook from `introduction-to-data-engineering`, from `week-05/materials`, or from `week-05/student_work`.

## A table small enough to check

In [3]:
import pandas as pd

df_small = pd.DataFrame(
    {
        "country": ["Finland", "Finland", "Japan", "Japan"],
        "year": [2019, 2020, 2019, 2020],
        "gdp": [240, 250, 5100, 5000],
    }
)
df_small

   country  year   gdp
0  Finland  2019   240
1  Finland  2020   250
2    Japan  2019  5100
3    Japan  2020  5000

## Basic `groupby`

`.size()` counts rows per country. `.min()` and `.max()` run inside each country. Finland's smallest GDP in this table is 240. Japan's is 5000.

In [4]:
df_small.groupby("country").size() # return in total COUNTS for groupby 'country' --> type: method
df_small.groupby("year").size()    # return in total COUNTS for groupby 'year'    --> type: method
df_small.groupby("gdp").size()     # return in total COUNTS for groupby 'gdp'     --> type: method
# type(df_small.groupby("gdp").size) --> method

gdp
240     1
250     1
5000    1
5100    1
dtype: int64

In [5]:
df_small.groupby("country")["gdp"].min() #       --> Series
# type(df_small.groupby("country")["gdp"].min()) --> Series

country
Finland     240
Japan      5000
Name: gdp, dtype: int64

In [6]:
df_small.groupby("country")["gdp"].max() #       --> Series
# type(df_small.groupby("country")["gdp"].max()) --> Series

country
Finland     250
Japan      5100
Name: gdp, dtype: int64

`agg` names each result. `as_index=False` keeps `country` as a normal column, which a later merge can use as a key.

In [7]:
# option 1:
summary_small = df_small.groupby("country", as_index=False).agg(
    first_year=("year", "min"),
    last_year=("year", "max"),
    min_gdp=("gdp", "min"),
    max_gdp=("gdp", "max"),
)
summary_small

# option 2:
summary2 = df_small.groupby("country",as_index=False)['year'].agg(["min",'max'])
summary3 = df_small.groupby("country",as_index=False)['gdp'].agg(["min",'max'])
summary4 = pd.merge(summary2, summary3, on="country", suffixes=("_year", "_gdp"))
summary4

   country  min_year  max_year  min_gdp  max_gdp
0  Finland      2019      2020      240      250
1    Japan      2019      2020     5000     5100

## Three Maddison countries

Same `groupby`, now on Finland, Sweden, and Japan. Stack the files first, as in the concat notebook.

In [8]:
from pathlib import Path


def find_existing(candidates):
    for path in candidates:
        if path.exists():
            return path
    searched = "\n".join(str(path) for path in candidates)
    raise FileNotFoundError(
        "Could not find the Maddison folder. Looked in:\n" + searched
    )


cwd = Path.cwd()
maddison_dir = find_existing(
    [
        cwd / "maddison_by_country",
        cwd / "materials/maddison_by_country",
        cwd / "week-05/materials/maddison_by_country",
        cwd / "../materials/maddison_by_country",
        cwd / "week-03/materials/maddison_by_country",
        cwd / "../../week-03/materials/maddison_by_country",
    ]
)
names = ["Finland", "Sweden", "Japan"]
frames = [pd.read_csv(maddison_dir / f"{name}.csv") for name in names]
df = pd.concat(frames, ignore_index=True)
df["Entity"].unique(), len(df)

(<StringArray>
 ['Finland', 'Sweden', 'Japan']
 Length: 3, dtype: str,
 519)

In [9]:
df

      Entity Code  Year            GDP  GDP (Annotations)
0    Finland  FIN  1600      476400000                NaN
1    Finland  FIN  1700      532400000                NaN
2    Finland  FIN  1820     1534897000                NaN
3    Finland  FIN  1850     2472932000                NaN
4    Finland  FIN  1860     2645236000                NaN
..       ...  ...   ...            ...                ...
514    Japan  JPN  2018  4852985093686                NaN
515    Japan  JPN  2019  4833467877373                NaN
516    Japan  JPN  2020  4626661481209                NaN
517    Japan  JPN  2021  4725883595048                NaN
518    Japan  JPN  2022  4774494846664                NaN

[519 rows x 5 columns]

In [10]:
country_stats = df.groupby("Entity", as_index=False).agg(
    first_year=("Year", "min"),
    last_year=("Year", "max"),
    min_gdp=("GDP", "min"),
    max_gdp=("GDP", "max"),
)
country_stats

    Entity  first_year  last_year     min_gdp        max_gdp
0  Finland        1600       2022   476400000   226154847456
1    Japan        1000       2022  7572375183  4852985093686
2   Sweden        1500       2022   956080000   494214521158

## In depth: the year of the min and the max

`min_gdp` is the value. `idxmin` finds the row, and the `Year` on that row is when it happened. Merge that year back onto `country_stats` on `Entity`.

Japan's latest year is 2022. Japan's largest GDP is in 2018. Finland and Sweden have their largest GDP in 2022, the last year in the file.

In [11]:
low_labels = df.groupby("Entity")["GDP"].idxmin() # Integer Index of the Min GDP, groupby country
print(low_labels) # a Series

high_labels = df.groupby("Entity")["GDP"].idxmax() # Integer Index of the Max GDP, groupby country
print(high_labels) # a Series

year_of_min = df.loc[low_labels, ["Entity", "Year"]].rename(columns={"Year": "year_of_min_gdp"}) # loc[row Indices, 2 columns shown], rename column
print(year_of_min) # a DataFrame!!

year_of_max = df.loc[high_labels, ["Entity", "Year"]].rename(columns={"Year": "year_of_max_gdp"}) # loc[row Indices, 2 columns shown], rename column
print(year_of_max)
pd.merge(country_stats, year_of_min, on="Entity") # merge the 2 dataframe into single one on 'Entity'.

# stats = country_stats.merge(year_of_min, on="Entity").merge(year_of_max, on="Entity")

Entity
Finland      0
Japan      373
Sweden     168
Name: GDP, dtype: int64
Entity
Finland    166
Japan      514
Sweden     372
Name: GDP, dtype: int64
      Entity  year_of_min_gdp
0    Finland             1600
373    Japan             1000
168   Sweden             1600
      Entity  year_of_max_gdp
166  Finland             2022
514    Japan             2018
372   Sweden             2022

    Entity  first_year  last_year     min_gdp        max_gdp  year_of_min_gdp
0  Finland        1600       2022   476400000   226154847456             1600
1    Japan        1000       2022  7572375183  4852985093686             1000
2   Sweden        1500       2022   956080000   494214521158             1600

In [12]:
stats = pd.merge(country_stats, year_of_min, on="Entity") # continue to merge the 3rd table. Merge cannot perform more than 2 tables at the same time.
stats = pd.merge(stats, year_of_max, on="Entity") # merge stats to stats on Entity
stats

,Entity,first_year,last_year,min_gdp,max_gdp,year_of_min_gdp,year_of_max_gdp
0,Finland,1600,2022,476400000,226154847456,1600,2022
1,Japan,1000,2022,7572375183,4852985093686,1000,2018
2,Sweden,1500,2022,956080000,494214521158,1600,2022

## Basic `merge`

`concat` stacks rows. `merge` matches a key and adds columns from the other table.

Both tables below use the same countries, so every row finds a match.

In [13]:
population = pd.DataFrame(
    {
        "country": ["Finland", "Japan", "Bhutan"],
        "population": [5_620_000, 123_975_000, 790_000],
    }
)
gdp = pd.DataFrame(
    {
        "country": ["Finland", "Japan", "Bhutan"],
        "gdp": [300, 4200, 3.0],
    }
)
pd.merge(population, gdp, on="country")

   country  population     gdp
0  Finland     5620000   300.0
1    Japan   123975000  4200.0
2   Bhutan      790000     3.0

## `inner`, `left`, and `outer`

Tuvalu is only in `population`. Suriname is only in `gdp_gap`.

| `how` | rows you keep |
| --- | --- |
| `inner` | keys that appear on both sides |
| `left` | every row of the left table |
| `outer` | every key from either table |

A key that is missing on one side shows up as `NaN` in that side's columns. `how="right"` keeps every row of the right table.

In [14]:
population_gap = pd.DataFrame(
    {
        "country": ["Finland", "Japan", "Tuvalu"],
        "population": [5_620_000, 123_975_000, 10_000],
    }
)
gdp_gap = pd.DataFrame(
    {
        "country": ["Finland", "Japan", "Suriname"],
        "gdp": [300, 4200, 4.0],
    }
)
pd.merge(population_gap, gdp_gap, on="country", how="inner") # inner: Tulvalu and Suriname will disappear, since they do not appear in both tables.

   country  population     gdp
0  Finland     5620000   300.0
1    Japan   123975000  4200.0

In [15]:
pd.merge(population_gap, gdp_gap, on="country", how="left")

   country  population     gdp
0  Finland     5620000   300.0
1    Japan   123975000  4200.0
2   Tuvalu       10000     NaN

In [16]:
pd.merge(population_gap, gdp_gap, on="country", how="outer")

    country   population     gdp
0   Finland    5620000.0   300.0
1     Japan  123975000.0  4200.0
2  Suriname          NaN     4.0
3    Tuvalu      10000.0     NaN

## In depth: repeated keys multiply rows

The left table has two `Blue` rows. The right table has two `Blue` rows. Each left Blue matches each right Blue, so 2 × 2 = 4 Blue rows, plus one Red row.

In [17]:
students = pd.DataFrame({"color": ["Blue", "Blue", "Red"], "student": ["A", "B", "C"]})
print(students)
shades = pd.DataFrame({"color": ["Blue", "Blue", "Red"], "shade": ["sky", "sea", "stop"]})
print(shades)

color_merge = pd.merge(students, shades, on="color")
print(color_merge)

pd.concat([students, shades[['shade']]], axis=1)

  color student
0  Blue       A
1  Blue       B
2   Red       C
  color shade
0  Blue   sky
1  Blue   sea
2   Red  stop
  color student shade
0  Blue       A   sky
1  Blue       A   sea
2  Blue       B   sky
3  Blue       B   sea
4   Red       C  stop

  color student shade
0  Blue       A   sky
1  Blue       B   sea
2   Red       C  stop

In [18]:
len(students), len(shades), len(color_merge)

(3, 3, 5)

## Practice

`country_stats` is already in memory (Finland, Sweden, Japan).

1. Count the rows per `Entity` in `df` with `groupby` and `.size()`.
2. Left-merge the capital table below onto `country_stats`. Which entity has an empty `min_gdp`?
3. Repeat that merge with `how="inner"`. Which entity is dropped?

```python
capitals = pd.DataFrame(
    {
        "Entity": ["Finland", "Sweden", "Japan", "Atlantis"],
        "capital": ["Helsinki", "Stockholm", "Tokyo", "Unknown"],
    }
)
```

### 1. Count the rows per `Entity` in `df` with `groupby` and `.size()`.

In [23]:
df
rows = df.groupby('Entity').size() # group by "Entity" and count the number of rows for each Entity
print('- Number of rows on DataFrame country_stats:\n',rows)

- Number of rows on DataFrame country_stats:
 Entity
Finland    167
Japan      146
Sweden     206
dtype: int64

### 2. Left-merge the capital table below onto `country_stats`. Which entity has an empty `min_gdp`?

In [26]:
country_stats
capitals = pd.DataFrame(
    {
        "Entity": ["Finland", "Sweden", "Japan", "Atlantis"],
        "capital": ["Helsinki", "Stockholm", "Tokyo", "Unknown"],
    }
)
capitals

final_merge = pd.merge(country_stats, capitals, on="Entity",how='right')
final_merge
# Entity with empty min_gdp: 'Atlantis'. Atlantis is added to the new DataFrame because all entity Keys from the 'right' will be added.
# Meanwhile, there is no values for Atlantis in 4 columns ("first_year", "last_year", "min_gdp", "max_gdp").

     Entity  first_year  last_year       min_gdp       max_gdp    capital
0   Finland      1600.0     2022.0  4.764000e+08  2.261548e+11   Helsinki
1    Sweden      1500.0     2022.0  9.560800e+08  4.942145e+11  Stockholm
2     Japan      1000.0     2022.0  7.572375e+09  4.852985e+12      Tokyo
3  Atlantis         NaN        NaN           NaN           NaN    Unknown

### 3. Repeat that merge with `how="inner"`. Which entity is dropped?

In [ ]:
final_merge = pd.merge(country_stats, capitals, on="Entity",how='inner')
final_merge = pd.merge(country_stats, capitals, on="Entity") # DEFAULT: how = 'inner'
final_merge
# with how = 'inner': There is no common "Atlantis" between the 2 tables --> missing 'Atlantis'.

    Entity  first_year  last_year     min_gdp        max_gdp    capital
0  Finland        1600       2022   476400000   226154847456   Helsinki
1    Japan        1000       2022  7572375183  4852985093686      Tokyo
2   Sweden        1500       2022   956080000   494214521158  Stockholm

## Quiz

**1.** What does `df_small.groupby("country")["gdp"].min()` return?

- A) One smallest GDP for the whole table
- B) The smallest GDP inside each country --> CHECK
- C) The row where GDP is smallest
- D) The number of countries

**2.** `pd.merge(population, gdp, on="country")` keeps which rows when some countries appear on only one side?

- A) Every row of `population`
- B) Countries that appear in both tables --> CHECK (= default = 'inner')
- C) Every country from either table
- D) Only the first row of each table

**3.** You want every row of the left table, with `NaN` where the right table has no match. Which `how` is that?

- A) `"inner"`
- B) `"left"` --> CHECK
- C) `"outer"`
- D) `"cross"`

**4.** `students` has two rows with color Blue. `shades` has two rows with color Blue. An inner merge on `color` produces how many Blue rows?

- A) 2
- B) 3
- C) 4 --> CHECK
- D) 8

## Answer key

For the instructor. Remove this section before sharing the notebook if the quiz should be unseen.

**Quiz:** 1 B, 2 B, 3 B, 4 C.

**Practice:**

1. Finland 167, Sweden 206, Japan 146.
2. Atlantis. It is only in `capitals`, so a left merge keeps it and `min_gdp` is `NaN`. Put `capitals` on the left.
3. Atlantis is dropped. Inner keeps Finland, Sweden, and Japan.

```python
df.groupby("Entity").size()

pd.merge(capitals, country_stats, on="Entity", how="left")
pd.merge(capitals, country_stats, on="Entity", how="inner")
```