# Exploring The Star Wars Dataset with The Pandas Library

In [2]:
import pandas as pd

If you don't have the pandas library installed you can install it with uncommenting the following:

In [3]:
#!pip install pandas

If you have the data set in your computer, you can use the path. Remember to replace backslash to slash: \ -> /
For example: "C:\Users\user1\star_wars\star_wars\csv\characters.csv" becomes "C:/Users/user1/star_wars/star_wars/csv/characters.csv"
You can also download the library from the Internet

**Use pandas read_csv function to read in the data**

In [4]:
df_characters = pd.read_csv("https://raw.githubusercontent.com/planetacomputer/starwars-full/main/characters.csv")

**Examine the top 2 rows**

In [5]:
df_characters.head(2)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
1,2,Leia Organa,Human,Female,1.50,49.0,Brown,Brown,Light,19.0,Alderaan,35.0,A leader in the Rebel Alliance and twin sister...

**Print the column names**

In [6]:
df_characters.columns

Index(['id', 'name', 'species', 'gender', 'height', 'weight', 'hair_color',
       'eye_color', 'skin_color', 'year_born', 'homeworld', 'year_died',
       'description'],
      dtype='str')

**Print the datatypes**

In [7]:
df_characters.dtypes

id               int64
name               str
species            str
gender             str
height         float64
weight         float64
hair_color         str
eye_color          str
skin_color         str
year_born      float64
homeworld          str
year_died      float64
description        str
dtype: object

## Exercises

### Selecting columns

Select only one column

In [8]:
df_characters[["name"]].head(3)

             name
0  Luke Skywalker
1     Leia Organa
2     Darth Vader

Select multiple columns:

In [9]:
df_characters[["name","species","gender","height"]].head(3)

             name species  gender  height
0  Luke Skywalker   Human    Male    1.72
1     Leia Organa   Human  Female    1.50
2     Darth Vader   Human    Male    2.02

Extra exercise: first put the columns name in a list and then use the variable name instead

### Filtering

Select only lines where height is over 1.5 m

In [10]:
df_characters[df_characters["height"] > 1.5].head(3)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19.0,Tatooine,34.0,The main protagonist of the original trilogy.
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.

Under the hood pandas produces a boolean array and that is used to make selection

In [11]:
df_characters["height"] > 1.5

0      True
1     False
2      True
3     False
4      True
      ...
91     True
92     True
93     True
94     True
95    False
Name: height, Length: 96, dtype: bool

Filtering with multiple conditions when both conditions must be true, we use **&**. Syntax is the following: **df_characters[ (condition 1) & (condintion 2)]** Note that we use & instead of **and**.

In [12]:
df_characters[ ( df_characters["species"] == "Human") & ( df_characters["height"] > 2.0 ) ]

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.

**Pandas logical operators are:**

& = bitwise AND operator

| = bitwise OR operator

~ = bitwise NOT operator

We can combine the operators. Here we choose characters whose eye_color is **not** Blue nor Brown or whose hair color is white

In [30]:
df_characters[ (  ~ df_characters["eye_color"].isin(["Blue","Brown"]) ) | ( df_characters["hair_color"] == "White" ) ].head(5)

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41.0,Tatooine,4.0,The Sith Lord formerly known as Anakin Skywalker.
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896.0,Unknown,4.0,A wise and powerful Jedi Master.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29.0,Corellia,34.0,A smuggler turned hero in the Rebel Alliance.
6,7,Obi-Wan Kenobi,Human,Male,1.82,81.0,White,Blue-gray,Light,57.0,Stewjon,0.0,A Jedi Master who mentored Anakin and Luke Sky...
7,8,Emperor Palpatine,Human,Male,1.73,75.0,NaN,Yellow,Pale,82.0,Naboo,35.0,The Sith Lord who became Emperor of the galaxy.

In [33]:
df_characters["skin_color"].value_counts()

skin_color
Light         50
Green         10
Dark           9
Pale           7
Blue           6
Brown          4
Orange         4
Red            2
White          1
Gold           1
White/Blue     1
Gray           1
Name: count, dtype: int64

## EXERCISES

!!!!! **Exercise 1 - 6 you have to be able to present **without** computer, so learn them by ❤️** !!!!!

### Exercise 1 - ✏️🧠

Select from df_characters only columns **name, species, hair_color, eye_color**

In [ ]:
## Write your answer here

### Exercise 2 - ✏️🧠

Select from df_characters that are less than 1.0 meter

In [ ]:
## Write your answer here

### Exercise 3 - ✏️🧠

Select from df_characters whose skin color is **Green** and select only columns **name, species, gender**

In [ ]:
## Write your answer here

### Exercise 4 - ✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **Red**.

In [ ]:
## Write your answer here

### Exercise 5 -✏️🧠

Select characters whose **eye_color** is **Blue** and whose **hair_color** is **NOT** **Red**.

In [ ]:
## Write your answer here

### Exercise 6 - ✏️🧠

Find all characters who are taller than 180 cm AND weigh more than 80 kg.

In [39]:
## Write your answer here

### Exercise 7 - 💻 ✅

Hint: You can use isin() function to filter through a list: df_characters[df_characters["eye_color"].isin(["Blue","Brown"])]

Select characters whose **eye_color** is not either **Blue** or **Brown**, and whose **hair_color** is **Green**.

In [42]:
## Write you answer to here

### Exercise 8 - 💻 ✅

Find characters who are taller than 180 cm, are not human, and do not weigh more than 100 kg.

In [41]:
## Write your answer to here

### Exercise 9 - 💻 ✅

Find characters who are either female and taller than 160 cm, OR male and taller than 190 cm.

In [43]:
## Write your answer to here

### Exercise 10 - 💻 ✅

**Let's take a subset of the data**

In [23]:
df_droids = df_characters[df_characters["species"] == "Droid"][["name","homeworld","description"]]

There are 4 droids

In [48]:
df_droids

     name homeworld                                        description
18   BB-8       NaN                       A spherical astromech droid.
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 1**: What is happening in the code below? Which lines are selected and why?

In [51]:
df_droids[[False,True,True,True]]

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

**Question 2**: Why does this code produce the similar output?

In [52]:
df_droids[df_droids["name"].str.len() == 5]

     name homeworld                                        description
19  C-3PO  Tatooine  A protocol droid fluent in over six million fo...
20  R2-D2     Naboo  An astromech droid known for his bravery and r...
92  L3-37   Unknown                       A self-built piloting droid.

### Bonus exercise 🐇🕳️

First make sure **numpy** is installed

In [53]:
!pip install numpy

Requirement already satisfied: numpy in /home/harttu/venv/lib/python3.12/site-packages (2.4.3)

In [55]:
import numpy as np

There is a problem in this code. Google/Use LLM to find out why it doesn't work.

In [56]:
df_droids[([True,False,True,False]) & ([False,True,False,False])]

TypeError: unsupported operand type(s) for &: 'list' and 'list'

However this works

In [57]:
np.array([True, False, True, False]) & np.array([False, True, False, False])

array([False, False, False, False])

**Question 1**: Use that syntax to make the original failing df_droid selection work?

**Question 2**: What does this tell about inner working of pandas? Does it work with numpy or basic python under the hood?